FROM maven:3.8.3-openjdk-17 AS build

WORKDIR /opt
COPY . .

RUN rm -f src/main/resources/application.properties && \
    cp -f application.properties src/main/resources/application.properties

RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jdk-jammy
WORKDIR /app

COPY --from=build /opt/target/student-registration-backend-0.0.1-SNAPSHOT.jar .

EXPOSE 8081

COPY wait-for-it.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/wait-for-it.sh

CMD ["wait-for-it.sh", "mariadb:3306", "--", "java", "-jar", "student-registration-backend-0.0.1-SNAPSHOT.jar"]
